integration with Yealink headsets, use webhid
purecloudlabs/softphone-vendor-headsets pull request #55
Opened 2022-06-09 11:55 UTC by Jaycan-YL

2022-06-14 13:16 UTC, djhouseknecht commented
I'm going to defer the finally approval to @jensengar and @maxwellmooney13 since they did most of the work on this library. 

But could you add unit tests, @Jaycan-YL? We like to keep all our open source libraries up to 100% coverage where possible.

2022-08-11 17:06 UTC, jensengar requested changes
Nothing major, mostly just a few styling tweaks. We are in the process of ordering some headsets so we can do a sanity test on it, then we'll get it in. Thanks contributing!

2022-08-11 17:06 UTC, jensengar commented on react-app/src/library/services/vendor-implementations/yealink/yealink.ts
> +    this.logger.info(`send to dev ${value}`);
this should be a `debug` level log.

2022-09-13 16:15 UTC, maxwellmooney13 commented
I have tested with five different YeaLink devices (UH38 Dual UC, UH36 Mono, UH34 Dual, WH62 Mono UC, WH66 Dual UC) and everything seems to work great!  I did notice with the WH62 that when I ended a call at one point, it also muted the call.  Not a huge deal but it is something I saw and was definitely strange to see.  Once Garrett's comments are addressed, you guys should be good to go! Thank you for your time, effort and patience in this.

Sidenote: We recently had an issue with a feature we offer for "auto answering calls".  I included functionality for this in a recent PR and it might be a good thing to quickly test and ensure auto answer works as expected for your devices as well.

2022-09-19 18:22 UTC, maxwellmooney13 commented
Did a very quick check with the auto answer capabilities and it seems fine from that perspective!  Might be good to do a quick double check on that though.  Otherwise, looks good!

2022-11-03 14:29 UTC, jensengar approved these changes

2022-11-03 18:44 UTC, merged